### ISSUE TITLE
Metadata Format

### ISSUE THREAD

**Issue by aularon** [smebberson/wintersmith-jade#5]
Using the format as specified by the README file (jade variables) does not work:
```jade
title = 'ηBits'
subtitle = 'etaBits Webs'
date = '2013/10/15'
teaser = 'etaBits is your ultimate online business partner, it helps your business whether it is internet-based or internet-promoted..'
template = 'index.jade'
```
Using the format from the example (.md metadata style), works:
```
---
title: 'within JADE'
template: index.jade
---
```

Please either update the code to use something other than `MarkdownPage.extractMetadata`, or revert the README file to show the right way, because the files won't render altogether using the new format.
Thanks for the useful plugin :+1:

**Comment by smebberson** [comment]
Fixed in #11.
